global:
    mode: global
    metrics:
        request:
            desc: Everytime we received a request, this counter will +1
        response:
            desc: Everytime we send a response, this counter will +1
        latency:
            desc: "This is the sum of the latency for each transcation (unit: micro-second)"
        connection:
            desc: The total connection amount
        uptime:
            desc: System uptime, every second +1

worker:
    mode: thread
    metrics:
        accept:
            desc: Accept counter (only for accept thread)
        request:
            desc: When the worker thread receive a request, this counter will +1
        response:
            desc: When the worker thread send a response, this coutner will +1
        latency:
            desc: "The sum of the latency for each transcation in the thread (unit: micro-second)"
        connection:
            desc: The total count of the entities in the thread


